# Generated by Django 2.2.3 on 2019-11-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_auto_20191126_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='market_value',
            field=models.CharField(blank=True, max_length=128, verbose_name='market_value'),
        ),
        migrations.AlterField(
            model_name='price',
            name='vol',
            field=models.CharField(blank=True, max_length=128, verbose_name='vol'),
        ),
    ]
