# Generated by Django 2.2.5 on 2019-11-01 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20191028_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='category',
        ),
        migrations.DeleteModel(
            name='NewsletterCat',
        ),
    ]
