# Generated by Django 2.2.3 on 2019-11-24 12:20

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='培训课程名称')),
                ('position', models.TextField(blank=True, max_length=200, verbose_name='培训地点')),
                ('acttime', models.TextField(blank=True, max_length=200, verbose_name='培训时间')),
                ('excerpt', models.TextField(blank=True, max_length=200, verbose_name='培训简介')),
                ('company', models.TextField(blank=True, max_length=200, verbose_name='培训单位')),
                ('author', models.CharField(max_length=70, verbose_name='培训发起人')),
                ('actfee', models.CharField(max_length=70, verbose_name='培训费用')),
                ('person', models.CharField(max_length=70, verbose_name='人数上限')),
                ('is_help', models.CharField(max_length=70, verbose_name='活动资助')),
                ('img', models.ImageField(blank=True, null=True, upload_to='article_img/%Y/%m/%d/', verbose_name='培训图片')),
                ('body', DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是开启活动')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '区块链培训',
                'verbose_name_plural': '区块链培训',
            },
        ),
    ]
