# Generated by Django 2.2.3 on 2019-11-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='author',
            field=models.CharField(max_length=70, verbose_name='培训讲师'),
        ),
    ]
