# Generated by Django 2.2.3 on 2019-11-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='is_help',
            field=models.CharField(max_length=70, verbose_name='活动资助'),
        ),
    ]
